"""First-run bootstrap for pip-installed users.

``trunkit quickstart`` closes the gap between ``pip install trunkit`` and a
working stack: it writes a docker-compose file for the two PostgreSQL
instances (trunk ledger on 5434, nerode workspace on 5435), starts them,
waits for readiness, applies both schemas, and prints next steps.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import time

import psycopg

from . import db as calx_db

COMPOSE_FILE = "docker-compose.yml"

COMPOSE_TEMPLATE = """\
# Generated by `trunkit quickstart`.
#   db-trunkit : proof ledger (calx/curry/kan/cert)  -> localhost:5434
#   db-nerode  : automata + Porter workspace         -> localhost:5435
# The two instances are separate by design — see SECURITY.md in the repo.
services:
  db-trunkit:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: trunk
      POSTGRES_PASSWORD: trunk
      POSTGRES_DB: trunk
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trunk -d trunk"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - trunk-pgdata:/var/lib/postgresql/data

  db-nerode:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nerode
      POSTGRES_PASSWORD: nerode
      POSTGRES_DB: nerode
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nerode -d nerode"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - nerode-pgdata:/var/lib/postgresql/data

volumes:
  trunk-pgdata:
  nerode-pgdata:
"""

NERODE_DSN = "postgresql://nerode:nerode@localhost:5435/nerode"


def ensure_compose_file(directory: pathlib.Path) -> tuple[pathlib.Path, bool]:
    """Write the compose template into *directory* unless one already exists.

    Returns (path, created). An existing file is never overwritten — a repo
    checkout already has its own compose file with an app service.
    """
    path = directory / COMPOSE_FILE
    if path.exists():
        return path, False
    directory.mkdir(parents=True, exist_ok=True)
    path.write_text(COMPOSE_TEMPLATE, encoding="utf-8")
    return path, True


def _compose_command() -> list[str] | None:
    """Return the available compose invocation, preferring the docker plugin."""
    if shutil.which("docker"):
        probe = subprocess.run(
            ["docker", "compose", "version"], capture_output=True, text=True
        )
        if probe.returncode == 0:
            return ["docker", "compose"]
    if shutil.which("docker-compose"):
        return ["docker-compose"]
    return None


def start_databases(compose_path: pathlib.Path) -> bool:
    cmd = _compose_command()
    if cmd is None:
        print("error: docker (or docker-compose) not found on PATH")
        print(f"  start the databases yourself with the compose file at {compose_path},")
        print("  or point $CALX_DSN / $NERODE_DSN at existing PostgreSQL instances")
        return False
    result = subprocess.run(
        [*cmd, "-f", str(compose_path), "up", "-d", "db-trunkit", "db-nerode"]
    )
    if result.returncode != 0:
        print("error: docker compose up failed (see output above)")
        return False
    return True


def wait_for(dsn: str, label: str, timeout: float = 90.0) -> bool:
    """Poll *dsn* until it accepts connections or *timeout* seconds elapse."""
    deadline = time.monotonic() + timeout
    print(f"  waiting for {label} …", end="", flush=True)
    while time.monotonic() < deadline:
        try:
            with psycopg.connect(dsn, connect_timeout=3):
                print(" ready")
                return True
        except psycopg.OperationalError:
            time.sleep(2)
    print(" timed out")
    print(f"error: {label} did not become ready within {timeout:.0f}s ({dsn})")
    return False


def apply_schemas(trunk_dsn: str | None, nerode_dsn: str) -> None:
    with calx_db.connect(trunk_dsn) as conn:
        calx_db.apply_unified(conn)
    print("  trunkit schema applied (calx/curry/kan/cert)")

    from nerode.db import apply_schema as nerode_apply_schema

    with psycopg.connect(nerode_dsn) as conn:
        nerode_apply_schema(conn)
    print("  nerode schema applied (automata/porter)")


def run(args) -> int:
    directory = pathlib.Path(args.dir).resolve()
    compose_path, created = ensure_compose_file(directory)
    verb = "wrote" if created else "found existing"
    print(f"{verb} {compose_path}")

    if args.compose_only:
        print("next: docker compose up -d, then `trunkit quickstart` again to apply schemas")
        return 0

    if not start_databases(compose_path):
        return 1

    trunk_dsn = calx_db.resolve_dsn(args.dsn)
    if not wait_for(trunk_dsn, "trunkit db (5434)") or not wait_for(
        NERODE_DSN, "nerode db (5435)"
    ):
        return 1

    apply_schemas(args.dsn, NERODE_DSN)

    print("\nquickstart complete. Try:")
    print("  trunkit generate --limit 100000 --backend pure")
    print("  trunkit standing")
    print('  nerode build --regex "(a|b)*abb" --write')
    return 0
