import psycopg, datetime
c = psycopg.connect("postgresql://trunk:trunk@localhost:5434/trunk")
cur = c.cursor()
cur.execute("SELECT count(*) FILTER (WHERE status IN ('valid','pass')), count(*) FILTER (WHERE status='refuted'), count(*) FILTER (WHERE status IN ('unverified','unchecked','error')), count(*) FROM cert.board")
v,f,u,t = cur.fetchone()
cur.execute("SELECT area,verified,failed,unknown,total FROM cert.board_summary")
rows = cur.fetchall()
cur.execute("SELECT area,plain,left(statement,86) FROM cert.board WHERE status IN ('refuted') ORDER BY area")
fails = cur.fetchall()
L = []
L.append("# Federation Status Board\n")
L.append(f"*One board for everything. Generated {datetime.date.today()} from the Trunkit cert ledger (`cert.board`). Green = checked & true, red = checked & false, grey = not yet checkable.*\n")
L.append(f"## Headline\n")
L.append(f"**✅ {v} verified · ❌ {f} failed · ❓ {u} unknown** &nbsp;(of {t} tracked claims)\n")
pct = round(100*v/t)
L.append(f"> {pct}% of everything tracked is independently verified right now.\n")
L.append("## By area\n")
L.append("| Area | ✅ verified | ❌ failed | ❓ unknown |")
L.append("|---|---:|---:|---:|")
for area,vv,ff,uu,tt in rows:
    L.append(f"| {area} | {vv} | {ff} | {uu} |")
L.append("")
if fails:
    L.append("## ❌ Needs attention (checked & failed)\n")
    for area,plain,stmt in fails:
        L.append(f"- **[{area}]** {stmt}")
    L.append("")
L.append("## What the colours mean\n")
L.append("- **✅ verified** — a probe ran and confirmed it (re-runnable; not an assertion).")
L.append("- **❌ failed** — a probe ran and it did *not* hold. A real, surfaced contradiction.")
L.append("- **❓ unknown** — honestly not yet checkable (no data, open problem, or tooling missing). *Never* shown as green.\n")
L.append("*Backed by one Postgres database; the `.curry`/`.lace`/per-method dotfiles are gone — methods are lenses (schemas) in the one ledger, not files.*")
open("C:/AI-Local/Trunk/STATUS.md","w",encoding="utf-8").write("\n".join(L))
print(f"wrote STATUS.md : {v} verified / {f} failed / {u} unknown / {t} total, {len(fails)} failures listed")
c.close()
