-- TEL renders calx (capability board pin).
--
-- A self-contained .tel program (generated by tel_calx_render.py from calx's
-- divisor data) draws the divisor-count bar chart and saves a PNG. This claim
-- verifies that render path end-to-end via tel_behavior_check.py (which confirms
-- a valid PNG is reproduced). Reads cert.tel_behavior. Idempotent.

INSERT INTO cert.claim (subject_kind, subject_ref, statement, claim_kind, method, probe_sql)
VALUES (
  'tel_graphics',
  '{"repo":"C:/AI-Local/tel-clean","program":"examples/calx_divisors.tel",
    "expect":"Return value: 0","produces":"bootstrap/output/calx_divisors.png"}'::jsonb,
  'TEL graphics: renders calx number theory (divisor bar chart) to a valid PNG',
  'computational', 'comp_sql', '')
ON CONFLICT (statement) DO NOTHING;

UPDATE cert.claim c SET probe_sql = format(
  $f$SELECT (CASE WHEN tb.status='valid'  THEN true
                  WHEN tb.status='failed' THEN false
                  ELSE NULL END) AS ok,
            jsonb_build_object('program', tb.program, 'expect', %L,
              'status', COALESCE(tb.status,'not_run'),
              'checked_at', tb.checked_at, 'detail', left(tb.detail,200)) AS evidence
       FROM (SELECT %s::int AS cid) q
       LEFT JOIN cert.tel_behavior tb ON tb.claim_id = q.cid$f$,
  c.subject_ref->>'expect', c.id)
WHERE c.subject_kind = 'tel_graphics'
  AND c.subject_ref->>'program' = 'examples/calx_divisors.tel';
